version: '3'
services:
  registry:
    image: registry:2
    networks:
      - default
    volumes:
      - /images:/var/lib/registry # store for container images

  proxy:
    image: nginx:alpine
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf # Nginx configuration file
      - $PWD/certs:/etc/nginx/certs/ # SSL certificate & public key
      - $PWD/auth:/etc/nginx/conf.d # nginx.htpasswd for container registry authentication, see Docker documentation
    ports:
      - 443:443
    networks:
      - default
      - production
      - staging
    environment:
      - PRODUCTION_SERVER_NAME=${PRODUCTION_SERVER_NAME}
      - STAGING_SERVER_NAME=${STAGING_SERVER_NAME}

networks:
  production:
    name: production
  staging:
    name: staging
